---
site_name: "aims-leaf"
theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      primary: amber
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: amber
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Data Model Overview: schema-overview.md
  - Background:
    - Overview: background/index.md
    - Project Context: background/project-context.md
    - Multiscale Data Integration: background/data-integration.md
    - AI/ML Framework: background/ai-ml-framework.md
  - Technical:
    - Data Model Direction: technical/data-model-direction.md
    - Roadmap: technical/roadmap.md
site_url: https://lambda-ber.github.io/aims-leaf
repo_url: https://github.com/lambda-ber/aims-leaf
